#!/usr/bin/env bash

gnome-session-inhibit --inhibit suspend ./analyze.php

# produce a flat file of influencers but with duplicates (influencer prio 1, influencer prio 2, influencer prio 3)
# print('create_allauthors')
gnome-session-inhibit --inhibit suspend ./create_allauthors.py

# print('toplongterminterests')
python3 toplongterminterests.py

python3 interest-applicationareas.py

python3 keywordcloud.py

python3 keywordgraph.py

./find_research_area.py

git add -A
git commit -m "update influencers and interests"
git push

